[package]
name = "mdbook-pagetoc"
version = "0.1.1"
edition = "2021"
description = "A mdbook plugin that provides a table of contents for each page."
homepage = "https://github.com/slowsage/mdbook-pagetoc"
repository = "https://github.com/slowsage/mdbook-pagetoc"
documentation = "https://github.com/slowsage/mdbook-pagetoc"
readme = "README.md"
license = "MPL-2.0"
keywords = ["mdbook", "table", "contents",  "pagetoc", "toc"]
exclude = [".github/"]

[dependencies]
mdbook = { version = "0.4.18", default-features = false }
clap = "3.1.8"
serde_json = "1.0.79"
semver = "1.0.7"
anyhow = "1.0.56"
log = "0.4.16"
env_logger = "0.9.0"
