[package]
name = "mdbook-pagetoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.17"
clap = "3.1.8"
serde_json = "1.0.79"
semver = "1.0.7"
anyhow = "1.0.56"
log = "0.4.16"
env_logger = "0.9.0"
