[package]
name = "mdbook-pagetoc"
version = "0.1.7"
edition = "2021"
description = "A mdbook plugin that provides a table of contents for each page."
homepage = "https://github.com/slowsage/mdbook-pagetoc"
repository = "https://github.com/slowsage/mdbook-pagetoc"
documentation = "https://github.com/slowsage/mdbook-pagetoc"
readme = "README.md"
license = "MPL-2.0"
keywords = ["mdbook", "table", "contents",  "pagetoc", "toc"]
exclude = [".github/"]

[dependencies]
mdbook = { version = "0.4.27", default-features = false }
clap = "4.1.8"
serde_json = "1.0.93"
semver = "1.0.16"
anyhow = "1.0.69"
log = "0.4.17"
env_logger = "0.10.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
