# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {target: x86_64-unknown-linux-gnu, binext: "",zipext: ".tar.gz"}
          - {target: x86_64-unknown-linux-musl, binext: "", zipext: ".tar.gz"}
          - {target: x86_64-pc-windows-gnu, binext: ".exe", zipext: ".zip"}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.platform.target }}

      - run: echo "BINARY_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].targets[] | select( .kind | map(. == "bin") | any ) | .name')" >> $GITHUB_ENV

      - if: ${{ matrix.platform.zipext == '.tar.gz' }}
        run: tar -zcvf ${{env.BINARY_NAME}}-${{github.ref_name}}-${{matrix.platform.target}}.tar.gz -C target/${{matrix.platform.target}}/release ${{env.BINARY_NAME}}${{matrix.platform.binext}}

      - if: ${{ matrix.platform.zipext == '.zip' }}
        run: 7z a ${{env.BINARY_NAME}}-${{github.ref_name}}-${{matrix.platform.target}}.zip ./target/${{matrix.platform.target}}/release/${{env.BINARY_NAME}}${{matrix.platform.binext}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.BINARY_NAME}}-${{github.ref_name}}-${{matrix.platform.target}}${{matrix.platform.zipext}}
